hamiltonian: heisenberg
load: false
n_sites: 8
t: 0.25
J: 
- 1.
- 1.
- -0.5
h: 
- 0.75
- 0.
- 0.
disordered: false
degree: 2
n_repetitions: 3
is_TI: true
truncation_dim: 64
rel_tol: 1.0e-11
abs_tol: 1.0e-14
n_samples_train: 16
n_samples_test: 96
cost: HST
optimizer: trust-region
n_iter: 10
radius_init: 0.01
maxradius: 0.5
