hamiltonian: ising-1d
load: false
n_sites: 8
t: 2.
J: 1.0
g: 0.75
h: 0.6
disordered: false
is_TI: true
degree: 2
n_repetitions: 3
truncation_dim: 32
rel_tol: 1.0e-11
abs_tol: 1.0e-14
n_samples_train: 16
n_samples_test: 96
cost: HST
optimizer: adam
n_iter: 500
lr: 5.0e-2